# Generated by Django 4.1.1 on 2022-09-28 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dairyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DairyPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='写真のタイトル')),
                ('date', models.DateField(blank=True)),
                ('image', models.ImageField(upload_to='images')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dairyPicture', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
