# Generated by Django 4.1.1 on 2022-10-03 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dairyApp', '0003_rename_user_id_dairycontent_user_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairypicture',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PictureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='カテゴリーのタイトル')),
                ('comment', models.TextField(blank=True, null=True)),
                ('picture_num', models.IntegerField(default=0)),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictureCategory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dairypicture',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dairyPicture', to='dairyApp.picturecategory'),
        ),
    ]
