# Generated by Django 4.1.1 on 2022-10-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyApp', '0004_dairypicture_comment_picturecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturecategory',
            name='comment',
            field=models.TextField(blank=True, max_length='200', null=True),
        ),
    ]
