# Generated by Django 4.1.1 on 2022-10-04 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dairyApp', '0005_alter_picturecategory_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturecategory',
            name='user_object',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictureCategory', to=settings.AUTH_USER_MODEL),
        ),
    ]
