# Generated by Django 4.1.1 on 2022-10-04 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyApp', '0006_alter_picturecategory_user_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picturecategory',
            old_name='picture_num',
            new_name='picture_count',
        ),
    ]
