# Generated by Django 4.1.1 on 2022-10-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyApp', '0007_rename_picture_num_picturecategory_picture_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairypicture',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
